(()=>{const root=document.getElementById('zeroGame');if(!root)return;const c=document.getElementById('zeroCourt'),x=c.getContext('2d'),toast=document.getElementById('shotToast'),cue=document.getElementById('contactCue');const W=720,H=1280;let running=false,practice=false,last=0,you=0,opp=0,server=2;let player={x:360,y:1050,targetX:360},enemy={x:360,y:220,targetX:360};let ball={x:360,y:890,vx:0,vy:0,z:18,vz:0,side:'you',live:false,lastHit:'enemy'};let touch=null,canHit=false;let paddle='VATIC PRO';const admin=root.dataset.admin==='1';const paddles=[['VATIC PRO','Basic • balanced control'],['BOOMSTIK','Trial • explosive pop'],['RPM','Trial • crisp all-court'],['LOCO','Trial • quick hands']];
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function vibrate(ms){try{navigator.vibrate&&navigator.vibrate(ms)}catch(e){}}function say(t,kind=''){toast.textContent=t;toast.className='zero-toast '+kind;clearTimeout(say.t);say.t=setTimeout(()=>toast.className='zero-toast',650)}
function resetBall(to='you'){ball={x:360,y:to==='you'?700:580,vx:0,vy:to==='you'?5.2:-5.2,z:96,vz:1.8,side:to,live:true,lastHit:to==='you'?'enemy':'you'};canHit=false}
function start(isPractice=false){practice=isPractice;running=true;you=0;opp=0;server=2;syncScore();say(isPractice?'PRACTICE • SWIPE TO HIT':'0-0-2 • PLAY','good');resetBall('you')}
function syncScore(){document.getElementById('scoreYou').textContent=you;document.getElementById('scoreOpp').textContent=opp;document.getElementById('serverNo').textContent=server}
function point(who){if(practice){say(who==='you'?'NICE BALL':'RESET');setTimeout(()=>resetBall('you'),500);return}if(who==='you')you++;else opp++;syncScore();say(who==='you'?'POINT!':'OPPONENT POINT',who==='you'?'good':'bad');if((you>=11||opp>=11)&&Math.abs(you-opp)>=2){running=false;setTimeout(()=>say(you>opp?'MATCH WON • +PROGRESS':'MATCH LOST • TRY AGAIN',you>opp?'good':'bad'),250);return}setTimeout(()=>resetBall(who==='you'?'opp':'you'),650)}
function shot(dx,dy,dt){if(!running||!canHit)return;const dist=Math.hypot(dx,dy),speed=dist/Math.max(dt,1);let type='DROP';if(dist>145&&speed>1.0)type='DRIVE';else if(dist<115&&speed>1.15)type='LOB';else if(player.y<820&&dist<105)type='DINK';const aim=clamp(dx/180,-1,1);let power=type==='DRIVE'?10.5:type==='LOB'?7.0:type==='DINK'?4.9:6.2;const timing=Math.abs(ball.y-player.y);const quality=clamp(1-timing/220,.68,1);ball.vy=-power*quality;ball.vx=aim*(type==='DRIVE'?4.5:3.0);ball.vz=type==='LOB'?9.2:type==='DRIVE'?5.6:type==='DINK'?3.9:4.7;ball.z=28;ball.lastHit='you';canHit=false;cue.classList.remove('ready');vibrate(quality>.85?18:8);say((quality>.88?'PERFECT ':'')+type,quality>.88?'good':'');}
function aiHit(){const err=(Math.random()-.5)*1.8;const attack=ball.z>34&&Math.random()>.42;ball.vy=attack?8.3:5.8;ball.vx=clamp((player.x-enemy.x)/160,-3.2,3.2)+err;ball.vz=attack?4.8:4.2;ball.z=28;ball.lastHit='enemy';enemy.targetX=clamp(ball.x,115,605)}
function update(dt){if(!running)return;player.x+=(player.targetX-player.x)*.13;enemy.x+=(enemy.targetX-enemy.x)*.08;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.z+=ball.vz*dt;ball.vz-=.16*dt;if(ball.z<0){ball.z=0;ball.vz=Math.abs(ball.vz)*.55;ball.vy*=.94;ball.vx*=.96}if(ball.x<65||ball.x>655){point(ball.lastHit==='you'?'opp':'you');ball.live=false;return}if(ball.live&&ball.lastHit==='enemy'&&ball.y>745){const near=Math.abs(ball.y-player.y)<230&&Math.abs(ball.x-player.x)<240;canHit=near;cue.classList.toggle('ready',near);if(ball.y>1210){ball.live=false;point('opp')}}if(ball.live&&ball.lastHit==='you'&&ball.y<390){if(Math.abs(ball.y-enemy.y)<90&&Math.abs(ball.x-enemy.x)<190){aiHit()}else if(ball.y<55){ball.live=false;point('you')}}if(ball.live&&ball.y>610&&ball.y<650&&ball.z<22){ball.live=false;point(ball.lastHit==='you'?'opp':'you');say('NET','bad')}if(ball.live&&ball.y<630&&ball.y>590&&ball.z<22){ball.live=false;point(ball.lastHit==='you'?'opp':'you');say('NET','bad')}}
function draw(){x.clearRect(0,0,W,H);x.fillStyle='#174b3b';x.fillRect(0,0,W,H);x.strokeStyle='rgba(255,255,255,.9)';x.lineWidth=7;x.strokeRect(55,45,610,1190);x.beginPath();x.moveTo(55,620);x.lineTo(665,620);x.stroke();x.fillStyle='rgba(83,167,127,.55)';x.fillRect(55,450,610,340);x.strokeStyle='rgba(255,255,255,.8)';x.lineWidth=5;x.beginPath();x.moveTo(55,450);x.lineTo(665,450);x.moveTo(55,790);x.lineTo(665,790);x.moveTo(360,45);x.lineTo(360,450);x.moveTo(360,790);x.lineTo(360,1235);x.stroke();x.fillStyle='rgba(0,0,0,.22)';x.fillRect(50,611,620,18);drawPerson(enemy.x,enemy.y,'#202020',false);drawPerson(player.x,player.y,'#f2f2f2',true);if(ball.live){x.beginPath();x.fillStyle='rgba(0,0,0,.18)';x.ellipse(ball.x,ball.y+12,13,6,0,0,Math.PI*2);x.fill();x.beginPath();x.fillStyle='#dfff32';x.arc(ball.x,ball.y-ball.z,13,0,Math.PI*2);x.fill()}}
function drawPerson(px,py,color,me){x.save();x.translate(px,py);x.fillStyle='rgba(0,0,0,.18)';x.beginPath();x.ellipse(0,25,34,12,0,0,Math.PI*2);x.fill();x.fillStyle=color;x.beginPath();x.arc(0,-20,22,0,Math.PI*2);x.fill();x.fillRect(-25,0,50,55);x.fillStyle=me?'#d71920':'#eee';x.fillRect(23,5,9,50);x.restore()}
function loop(t){const dt=Math.min((t-last)/16.67||1,2);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function pos(e){const r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)/r.width*W,y:(p.clientY-r.top)/r.height*H}}
c.addEventListener('pointerdown',e=>{const p=pos(e);touch={...p,t:performance.now()};if(!canHit){player.targetX=clamp(p.x,110,610)}});c.addEventListener('pointermove',e=>{if(!touch||canHit)return;const p=pos(e);player.targetX=clamp(p.x,110,610)});c.addEventListener('pointerup',e=>{if(!touch)return;const p=pos(e),dt=performance.now()-touch.t;shot(p.x-touch.x,touch.y-p.y,dt);touch=null});document.getElementById('startMatchBtn').onclick=()=>start(false);document.getElementById('practiceBtn').onclick=()=>start(true);
const modal=document.getElementById('paddleModal'),list=document.getElementById('paddleList');function renderPaddles(){list.innerHTML='';paddles.forEach((p,i)=>{const unlocked=admin||i===0||true;const b=document.createElement('button');b.className='zero-paddle '+(paddle===p[0]?'active':'');b.innerHTML='<b>'+p[0]+'</b><small>'+p[1]+'</small>';b.onclick=()=>{if(!unlocked)return;paddle=p[0];document.getElementById('paddleBtn').textContent=paddle;modal.hidden=true;say(paddle+' EQUIPPED','good')};list.appendChild(b)})}document.getElementById('paddleBtn').onclick=()=>{renderPaddles();modal.hidden=false};document.getElementById('closePaddles').onclick=()=>modal.hidden=true;draw();})();
