<?php
require __DIR__.'/includes/app.php';
requireAdmin();
$month=$_GET['month']??date('Y-m');if(!preg_match('/^\d{4}-\d{2}$/',$month)||!strtotime($month.'-01'))$month=date('Y-m');
$events=sessionsForMonth($pdo,$month);$byDate=[];foreach($events as $e)$byDate[$e['scheduled_date']][]=$e;
$first=$month.'-01';$days=(int)date('t',strtotime($first));$lead=(int)date('w',strtotime($first));$prev=date('Y-m',strtotime($first.' -1 month'));$next=date('Y-m',strtotime($first.' +1 month'));
$activePage='calendar';$pageTitle='Calendar - RS8 Pickleball';require __DIR__.'/includes/header.php';
function cal141State(array $e): string { if(($e['status']??'')==='cancelled')return 'cancelled';return scheduleDisplayState($e); }
function cal141Label(array $e): string { if(($e['status']??'')==='cancelled')return 'CANCELLED';return scheduleDisplayLabel($e); }
?>
<div class="page-title"><h1>Court Calendar</h1><p>Tap any date to open all Court 1 bookings for that day.</p></div>
<section class="section"><div class="calendar-legend"><span><i class="upcoming"></i>UPCOMING</span><span><i class="ongoing"></i>ONGOING</span><span><i class="ended"></i>ENDED</span><span><i class="cancelled-dot"></i>CANCELLED</span></div><div class="calendar-head"><a class="mini" href="calendar.php?month=<?=$prev?>">‹ PREV</a><div><b><?=date('F Y',strtotime($first))?></b><small>COURT 1</small></div><a class="mini" href="calendar.php?month=<?=$next?>">NEXT ›</a></div>
<div class="calendar-grid weekdays"><?php foreach(['S','M','T','W','T','F','S'] as $d):?><div><?=$d?></div><?php endforeach;?></div><div class="calendar-grid month-grid">
<?php for($i=0;$i<$lead;$i++):?><div class="calendar-day blank"></div><?php endfor;?>
<?php for($day=1;$day<=$days;$day++):$date=$month.'-'.str_pad((string)$day,2,'0',STR_PAD_LEFT);$dayEvents=$byDate[$date]??[];$today=$date===date('Y-m-d');?>
<button type="button" class="calendar-day calendar-day-open <?=$today?'today':''?> <?=$dayEvents?'has-events':''?>" data-calendar-open="cal-<?=esc($date)?>"><span class="day-no"><?=$day?></span><?php foreach(array_slice($dayEvents,0,2) as $e):$state=cal141State($e);?><span class="calendar-event calendar-event-preview <?=isCourtRental($e)?'rental':'openplay'?> <?=$state?>"><span></span><?=date('g:i',strtotime($e['scheduled_time']))?></span><?php endforeach;?><?php if(count($dayEvents)>2):?><small class="more-events">+<?=count($dayEvents)-2?></small><?php endif;?></button>
<dialog class="calendar-day-modal" id="cal-<?=esc($date)?>"><div class="calendar-day-sheet"><div class="calendar-day-sheet-head"><div><div class="eyebrow">COURT 1 • <?=strtoupper(date('D',strtotime($date)))?></div><h2><?=date('F j, Y',strtotime($date))?></h2></div><button type="button" class="calendar-modal-close" data-calendar-close>×</button></div><div class="calendar-day-sheet-body"><?php if(!$dayEvents):?><div class="empty">No bookings for this date.</div><?php endif;?><?php foreach($dayEvents as $e):$state=cal141State($e);?><a class="calendar-modal-booking <?=$state?>" href="schedule_view.php?id=<?=(int)$e['id']?>"><div><span class="eyebrow"><?=esc(strtoupper(scheduleTypeLabel($e['schedule_type']??'open_play')))?></span><b><?=esc($e['name'])?></b><small><?=prettyTime($e['scheduled_time'])?>–<?=prettyTime($e['scheduled_end_time'])?> • Court 1</small></div><span class="pill <?=$state==='ongoing'?'live':($state==='ended'?'ended-pill':($state==='cancelled'?'cancelled-pill':'upcoming-pill'))?>"><?=esc(cal141Label($e))?></span></a><?php endforeach;?><a class="btn ghost" href="schedule_edit.php?date=<?=esc($date)?>">+ ADD BOOKING ON THIS DATE</a></div></div></dialog>
<?php endfor;?></div></section>
<section class="section"><div class="section-head"><h2><?=strtoupper(date('F Y',strtotime($first)))?></h2><a class="mini primary" href="schedule_edit.php">+ ADD</a></div><?php if(!$events):?><div class="card empty">No court activity this month.</div><?php endif;?><?php foreach($events as $e):$state=cal141State($e);?><a class="card calendar-list-card <?=isCourtRental($e)?'rental-card':'openplay-card'?> calendar-<?=$state?>" href="schedule_view.php?id=<?=(int)$e['id']?>"><div><div class="eyebrow"><?=esc(strtoupper(scheduleTypeLabel($e['schedule_type']??'open_play')))?></div><b><?=esc($e['name'])?></b><div class="meta"><?=prettyDate($e['scheduled_date'])?> • <?=prettyTime($e['scheduled_time'])?>–<?=prettyTime($e['scheduled_end_time'])?></div></div><span class="pill <?=$state==='ongoing'?'live':($state==='ended'?'ended-pill':($state==='cancelled'?'cancelled-pill':'upcoming-pill'))?>"><?=esc(cal141Label($e))?></span></a><?php endforeach;?></section>
<script>document.querySelectorAll('[data-calendar-open]').forEach(function(b){b.addEventListener('click',function(){var d=document.getElementById(b.dataset.calendarOpen);if(d&&d.showModal)d.showModal();});});document.querySelectorAll('[data-calendar-close]').forEach(function(b){b.addEventListener('click',function(){var d=b.closest('dialog');if(d)d.close();});});document.querySelectorAll('.calendar-day-modal').forEach(function(d){d.addEventListener('click',function(e){if(e.target===d)d.close();});});</script>
<?php require __DIR__.'/includes/footer.php';
