<?php
require __DIR__.'/includes/app.php';
try{
    if($_SERVER['REQUEST_METHOD']==='POST'){
        verifyCsrf();$id=v1320CreateScheduleRequest($pdo,$_POST);$_SESSION['last_schedule_request_id']=$id;flashSet('ok','Schedule request sent. It is PENDING until an RS8 admin approves it.');go('request_schedule.php?sent=1');
    }
}catch(Throwable $e){flashSet('err',$e->getMessage());go('request_schedule.php');}
$activePage='home';$pageTitle='Request Court Schedule - RS8 Pickleball';$upcoming=[];try{$upcoming=upcomingScheduledSessions($pdo,40);}catch(Throwable $e){};require __DIR__.'/includes/header.php';
?>
<div class="page-title"><h1>Request Court Schedule</h1><p>See confirmed Court 1 bookings first, then request a preferred time. Requests do not reserve the court until an admin approves them.</p></div>
<section class="section"><div class="section-head"><h2>CONFIRMED COURT TIME</h2><span class="count"><?=count($upcoming)?> UPCOMING</span></div><div class="card compact public-schedule-list"><?php if(!$upcoming):?><div class="empty">No confirmed upcoming court schedule.</div><?php endif;?><?php foreach($upcoming as $s):?><div class="public-schedule-row"><div><b><?=isCourtRental($s)?'Court Rental • Reserved':esc($s['name'])?></b><div class="meta"><?=prettyDate($s['scheduled_date'])?> • <?=prettyTime($s['scheduled_time'])?>–<?=prettyTime($s['scheduled_end_time'])?></div></div><span class="pill <?=scheduleDisplayState($s)==='ongoing'?'live':'upcoming-pill'?>"><?=esc(scheduleDisplayLabel($s))?></span></div><?php endforeach;?></div></section>
<section class="section"><div class="section-head"><h2>REQUEST A SLOT</h2><span class="count">ADMIN APPROVAL</span></div><div class="card"><div class="notice info"><b>Important:</b> Sending a request does not guarantee the slot. Admin reviews conflicts and makes the final booking decision.</div><form method="post" class="form"><?=csrfField()?><label>Your Name / Group Representative</label><input name="requester_name" required placeholder="Full name"><label>Contact Number / Messenger Contact</label><input name="contact_number" required placeholder="How admin can contact you"><label>Request Type</label><select name="schedule_type"><option value="court_rental">Court Rental</option><option value="open_play">Open Play Request</option></select><label>Request / Group Name</label><input name="request_name" placeholder="Optional e.g. Boss J Group"><label>Date</label><input name="requested_date" type="date" min="<?=date('Y-m-d')?>" required><div class="two"><div><label>Start Time</label><input name="requested_time" type="time" required></div><div><label>End Time</label><input name="requested_end_time" type="time" required></div></div><label>Notes / Considerations</label><textarea name="notes" rows="3" placeholder="Optional details for admin review"></textarea><button class="btn">SUBMIT SCHEDULE REQUEST</button><a class="btn ghost" href="home.php">BACK HOME</a></form></div></section>
<?php require __DIR__.'/includes/footer.php';
