<?php
require __DIR__.'/includes/app.php';
$prefillDate=trim((string)($_GET['date']??$_POST['requested_date']??''));if($prefillDate!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$prefillDate))$prefillDate='';
try{if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrf();$id=v1320CreateScheduleRequest($pdo,$_POST);$_SESSION['last_schedule_request_id']=$id;flashSet('ok','Schedule request sent. It is PENDING until an RS8 admin approves it.');go('request_schedule.php?sent=1&date='.rawurlencode((string)($_POST['requested_date']??'')));}}catch(Throwable $e){flashSet('err',$e->getMessage());go('request_schedule.php'.($prefillDate!==''?'?date='.rawurlencode($prefillDate):''));}
$activePage='schedules';$pageTitle='Request Court Schedule - RS8 Pickleball';$all=[];try{$all=upcomingScheduledSessions($pdo,80);}catch(Throwable $e){};$sameDate=$prefillDate!==''?array_values(array_filter($all,fn($s)=>($s['scheduled_date']??'')===$prefillDate)):[];require __DIR__.'/includes/header.php';
?>
<div class="page-title"><h1>Request Court Schedule</h1><p><?=$prefillDate!==''?'Selected date: '.date('F j, Y',strtotime($prefillDate)).'. Review occupied times, then request your preferred slot.':'Choose your preferred date and time. Requests remain pending until Admin approval.'?></p></div>
<?php if($prefillDate!==''):?><section class="section"><div class="section-head"><h2>ALREADY BOOKED</h2><span class="count"><?=count($sameDate)?> SLOT<?=count($sameDate)===1?'':'S'?></span></div><div class="card compact"><?php if(!$sameDate):?><div class="empty">No confirmed booking on this date yet.</div><?php endif;?><?php foreach($sameDate as $s):?><div class="public-schedule-row"><div><b><?=prettyTime($s['scheduled_time'])?>–<?=prettyTime($s['scheduled_end_time'])?></b><div class="meta"><?=isCourtRental($s)?'Reserved Court Time':esc($s['name'])?> • Court 1</div></div><span class="pill upcoming-pill">BOOKED</span></div><?php endforeach;?></div></section><?php endif;?>
<section class="section"><div class="section-head"><h2>REQUEST A SLOT</h2><span class="count">ADMIN APPROVAL</span></div><div class="card"><div class="notice info"><b>Important:</b> Sending a request does not guarantee the slot. Admin reviews conflicts and makes the final booking decision.</div><form method="post" class="form"><?=csrfField()?><label>Your Name / Group Representative</label><input name="requester_name" required placeholder="Full name"><label>Contact Number / Messenger Contact</label><input name="contact_number" required placeholder="How admin can contact you"><label>Request Type</label><select name="schedule_type"><option value="court_rental">Court Rental</option><option value="open_play">Open Play Request</option></select><label>Request / Group Name</label><input name="request_name" placeholder="Optional e.g. Boss J Group"><label>Date</label><input name="requested_date" type="date" min="<?=date('Y-m-d')?>" value="<?=esc($prefillDate)?>" required><div class="two"><div><label>Start Time</label><input name="requested_time" type="time" required></div><div><label>End Time</label><input name="requested_end_time" type="time" required></div></div><label>Notes / Considerations</label><textarea name="notes" rows="3" placeholder="Optional details for admin review"></textarea><button class="btn">SUBMIT SCHEDULE REQUEST</button><a class="btn ghost" href="<?=$prefillDate!==''?'bookings.php?date='.esc($prefillDate):'bookings.php'?>">BACK TO BOOKINGS</a></form></div></section>
<?php require __DIR__.'/includes/footer.php';
