<?php
// RS8 Queue v1.3.20 consolidated behavior layer.
// Kept separate so the self-updater can safely add the new rotation/request model without redeclaring legacy helpers.

function v1320FindDuplicatePlayers(PDO $pdo,string $name,int $excludeId=0): array {
    $name=trim(preg_replace('/\s+/u',' ',$name));if($name==='')return [];
    $q=$pdo->prepare("SELECT p.*,COALESCE((SELECT SUM(sp.games_played) FROM session_players sp WHERE sp.player_id=p.id),0) total_games FROM players p WHERE LOWER(TRIM(p.name))=LOWER(TRIM(?)) AND p.id<>? ORDER BY p.is_active DESC,p.id ASC");
    $q->execute([$name,$excludeId]);return $q->fetchAll();
}
function v1320NicknameAvailable(PDO $pdo,string $name,string $nickname,int $excludeId=0): bool {
    $nickname=trim($nickname);if($nickname==='')return false;
    $q=$pdo->prepare("SELECT COUNT(*) FROM players WHERE LOWER(TRIM(name))=LOWER(TRIM(?)) AND LOWER(TRIM(COALESCE(nickname,'')))=LOWER(TRIM(?)) AND id<>?");$q->execute([trim($name),$nickname,$excludeId]);return (int)$q->fetchColumn()===0;
}
function v1320CreatePlayer(PDO $pdo,string $name,string $nickname,string $gender,string $level='NR',mixed $declaredDupr=null,bool $allowSameNameDifferentNickname=false): int {
    $name=trim(preg_replace('/\s+/u',' ',$name));if($name==='')throw new Exception('Player name is required.');$nickname=trim($nickname);$dups=v1320FindDuplicatePlayers($pdo,$name);
    if($dups){if(!$allowSameNameDifferentNickname)throw new Exception('Duplicate player found. Use the existing player, add a distinguishing nickname for a different person, or discard.');if($nickname==='')throw new Exception('A unique nickname is required for a different player with the same full name.');if(!v1320NicknameAvailable($pdo,$name,$nickname))throw new Exception('That full name + nickname already exists.');}
    if(!in_array($gender,['M','F','Other'],true))$gender='M';$dupr=normalizeDeclaredDupr($declaredDupr);$level=skillLevelFromDupr($dupr,$level);$seed=$dupr??seedRating($level);
    $q=$pdo->prepare("INSERT INTO players(name,nickname,gender,skill_level,dupr_rating,hidden_rating,is_active,updated_at) VALUES(?,?,?,?,?,?,1,NOW())");$q->execute([$name,$nickname,$gender,$level,$dupr,$seed]);return (int)$pdo->lastInsertId();
}

function v1320EnsureQueueOrder(PDO $pdo,int $sessionId): void {
    static $done=[];$key=spl_object_id($pdo).':'.$sessionId;if(isset($done[$key]))return;$done[$key]=true;
    $q=$pdo->prepare("SELECT COALESCE(MAX(queue_credit),0) FROM session_players WHERE session_id=?");$q->execute([$sessionId]);$next=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT id FROM session_players WHERE session_id=? AND queue_credit<=0 ORDER BY id");$q->execute([$sessionId]);$u=$pdo->prepare("UPDATE session_players SET queue_credit=? WHERE id=?");foreach($q->fetchAll() as $r){$next++;$u->execute([$next,(int)$r['id']]);}
}
function v1320NextQueueOrder(PDO $pdo,int $sessionId): int {$q=$pdo->prepare("SELECT COALESCE(MAX(queue_credit),0)+1 FROM session_players WHERE session_id=?");$q->execute([$sessionId]);return max(1,(int)$q->fetchColumn());}
function v1320PlayerRows(PDO $pdo,int $sessionId): array {
    v1320EnsureQueueOrder($pdo,$sessionId);$q=$pdo->prepare("SELECT sp.*,p.name,p.nickname,p.gender,p.skill_level,p.dupr_rating,p.hidden_rating,p.photo_url FROM session_players sp JOIN players p ON p.id=sp.player_id WHERE sp.session_id=? ORDER BY CASE WHEN sp.status='Waiting' THEN 0 ELSE 1 END,sp.queue_credit ASC,sp.id ASC");$q->execute([$sessionId]);return $q->fetchAll();
}
function v1320GenerateOnDeck(PDO $pdo,int $sessionId): ?int {
    $q=$pdo->prepare("SELECT id FROM matches WHERE session_id=? AND status='ondeck' LIMIT 1");$q->execute([$sessionId]);if($q->fetch())return null;
    $eligible=array_values(array_filter(v1320PlayerRows($pdo,$sessionId),fn($p)=>$p['status']==='Waiting'));if(count($eligible)<4)return null;
    $four=array_slice($eligible,0,4);[$partners,$opponents]=recentPairs($pdo,$sessionId);$options=pairingCandidates($four,$partners,$opponents);$pick=weightedRandomMatch($options)??($options[0]??null);if(!$pick)return null;
    $q=$pdo->prepare("INSERT INTO matches(session_id,court_no,status,a1,a2,b1,b2) VALUES(?,1,'ondeck',?,?,?,?)");$q->execute([$sessionId,$pick['A'][0]['player_id'],$pick['A'][1]['player_id'],$pick['B'][0]['player_id'],$pick['B'][1]['player_id']]);return (int)$pdo->lastInsertId();
}
function v1320StartOnDeck(PDO $pdo,int $sessionId): void {
    $q=$pdo->prepare("SELECT id FROM matches WHERE session_id=? AND status='active' LIMIT 1");$q->execute([$sessionId]);if($q->fetch())return;$q=$pdo->prepare("SELECT * FROM matches WHERE session_id=? AND status='ondeck' ORDER BY id LIMIT 1");$q->execute([$sessionId]);$m=$q->fetch();if(!$m)return;
    $pdo->prepare("UPDATE matches SET status='active',started_at=NOW() WHERE id=?")->execute([$m['id']]);foreach(['a1','a2','b1','b2'] as $c)$pdo->prepare("UPDATE session_players SET status='Playing' WHERE session_id=? AND player_id=?")->execute([$sessionId,$m[$c]]);v1320GenerateOnDeck($pdo,$sessionId);
}
function v1320InitializeQueue(PDO $pdo,int $sessionId): void {v1320EnsureQueueOrder($pdo,$sessionId);v1320GenerateOnDeck($pdo,$sessionId);v1320StartOnDeck($pdo,$sessionId);v1320GenerateOnDeck($pdo,$sessionId);}
function v1320CheckInPlayer(PDO $pdo,int $sessionId,int $playerId): void {
    addRosterPlayer($pdo,$sessionId,$playerId);$order=v1320NextQueueOrder($pdo,$sessionId);$q=$pdo->prepare("INSERT INTO session_players(session_id,player_id,status,queue_credit,games_since_last_played) VALUES(?,?,'Waiting',?,0) ON DUPLICATE KEY UPDATE queue_credit=IF(status='Checked Out',VALUES(queue_credit),queue_credit),status=IF(status='Checked Out','Waiting',status)");$q->execute([$sessionId,$playerId,$order]);v1320GenerateOnDeck($pdo,$sessionId);v1320StartOnDeck($pdo,$sessionId);v1320GenerateOnDeck($pdo,$sessionId);
}
function v1320ClearOnDeckIfContains(PDO $pdo,int $sessionId,int $playerId): bool {$q=$pdo->prepare("SELECT id FROM matches WHERE session_id=? AND status='ondeck' AND ? IN(a1,a2,b1,b2) LIMIT 1");$q->execute([$sessionId,$playerId]);$id=(int)($q->fetchColumn()?:0);if(!$id)return false;$pdo->prepare("DELETE FROM matches WHERE id=?")->execute([$id]);return true;}
function v1320ShuffleOnDeck(PDO $pdo,int $sessionId): void {
    $q=$pdo->prepare("SELECT * FROM matches WHERE session_id=? AND status='ondeck' LIMIT 1");$q->execute([$sessionId]);$m=$q->fetch();if(!$m)throw new Exception('There is no full On Deck match to shuffle yet.');$ids=array_map('intval',[$m['a1'],$m['a2'],$m['b1'],$m['b2']]);$four=matchPlayerRows($pdo,$sessionId,$ids);[$partners,$opponents]=recentPairs($pdo,$sessionId);$options=pairingCandidates($four,$partners,$opponents);
    $canon=function(array $A,array $B): string {$ta=array_map(fn($x)=>(int)$x['player_id'],$A);$tb=array_map(fn($x)=>(int)$x['player_id'],$B);sort($ta);sort($tb);$teams=[implode('-',$ta),implode('-',$tb)];sort($teams);return implode('|',$teams);};$current=$canon([$four[0],$four[1]],[$four[2],$four[3]]);$alts=array_values(array_filter($options,fn($o)=>$canon($o['A'],$o['B'])!==$current));if($alts)$options=$alts;$pick=weightedRandomMatch($options);if(!$pick)throw new Exception('Unable to shuffle On Deck.');$pdo->prepare("UPDATE matches SET a1=?,a2=?,b1=?,b2=? WHERE id=?")->execute([(int)$pick['A'][0]['player_id'],(int)$pick['A'][1]['player_id'],(int)$pick['B'][0]['player_id'],(int)$pick['B'][1]['player_id'],(int)$m['id']]);
}
function v1320SaveManualOnDeck(PDO $pdo,int $sessionId,array $ids): int {
    $rows=matchPlayerRows($pdo,$sessionId,$ids);foreach($rows as $r)if($r['status']!=='Waiting')throw new Exception(playerName($r).' is not available for On Deck.');$ids=array_map(fn($r)=>(int)$r['player_id'],$rows);$pdo->beginTransaction();try{$pdo->prepare("DELETE FROM matches WHERE session_id=? AND status='ondeck'")->execute([$sessionId]);$q=$pdo->prepare("INSERT INTO matches(session_id,court_no,status,a1,a2,b1,b2) VALUES(?,1,'ondeck',?,?,?,?)");$q->execute([$sessionId,...$ids]);$id=(int)$pdo->lastInsertId();$pdo->commit();return $id;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
function v1320SaveManualActive(PDO $pdo,int $sessionId,int $matchId,array $ids): void {
    $q=$pdo->prepare("SELECT * FROM matches WHERE id=? AND session_id=? AND status='active'");$q->execute([$matchId,$sessionId]);$active=$q->fetch();if(!$active)throw new Exception('Active match not found.');$rows=matchPlayerRows($pdo,$sessionId,$ids);foreach($rows as $r)if(in_array($r['status'],['Paused','Checked Out'],true))throw new Exception(playerName($r).' is not available.');$new=array_map(fn($r)=>(int)$r['player_id'],$rows);$old=array_map('intval',[$active['a1'],$active['a2'],$active['b1'],$active['b2']]);
    $pdo->beginTransaction();try{$d=$pdo->prepare("SELECT * FROM matches WHERE session_id=? AND status='ondeck' LIMIT 1");$d->execute([$sessionId]);$dm=$d->fetch();if($dm&&array_intersect($new,array_map('intval',[$dm['a1'],$dm['a2'],$dm['b1'],$dm['b2']])))$pdo->prepare("DELETE FROM matches WHERE id=?")->execute([$dm['id']]);$returnOrder=v1320NextQueueOrder($pdo,$sessionId);foreach($old as $pid)if(!in_array($pid,$new,true))$pdo->prepare("UPDATE session_players SET status='Waiting',queue_credit=? WHERE session_id=? AND player_id=?")->execute([$returnOrder++,$sessionId,$pid]);foreach($new as $pid)$pdo->prepare("UPDATE session_players SET status='Playing' WHERE session_id=? AND player_id=?")->execute([$sessionId,$pid]);$pdo->prepare("UPDATE matches SET a1=?,a2=?,b1=?,b2=? WHERE id=?")->execute([$new[0],$new[1],$new[2],$new[3],$matchId]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}v1320GenerateOnDeck($pdo,$sessionId);
}
function v1320FinishMatch(PDO $pdo,int $matchId,int $sa,int $sb): void {
    if($sa<0||$sb<0)throw new Exception('Scores cannot be negative.');if($sa===$sb)throw new Exception('Scores cannot be tied.');$q=$pdo->prepare("SELECT * FROM matches WHERE id=? AND status='active'");$q->execute([$matchId]);$m=$q->fetch();if(!$m)throw new Exception('Active match not found.');
    $pdo->beginTransaction();try{$winner=$sa>$sb?'A':'B';$pdo->prepare("UPDATE matches SET score_a=?,score_b=?,winner=?,status='completed',ended_at=NOW() WHERE id=?")->execute([$sa,$sb,$winner,$matchId]);$ids=array_map('intval',[$m['a1'],$m['a2'],$m['b1'],$m['b2']]);$next=v1320NextQueueOrder($pdo,(int)$m['session_id']);
        foreach($ids as $id){$isA=in_array($id,[(int)$m['a1'],(int)$m['a2']],true);$win=($winner==='A'&&$isA)||($winner==='B'&&!$isA);$pdo->prepare("UPDATE session_players SET status='Waiting',games_played=games_played+1,wins=wins+?,losses=losses+?,queue_credit=?,games_since_last_played=0 WHERE session_id=? AND player_id=?")->execute([$win?1:0,$win?0:1,$next++,$m['session_id'],$id]);}
        $ph=implode(',',array_fill(0,4,'?'));$rs=$pdo->prepare("SELECT id,hidden_rating FROM players WHERE id IN ($ph)");$rs->execute($ids);$rating=[];foreach($rs->fetchAll() as $r)$rating[(int)$r['id']]=(float)$r['hidden_rating'];$ra=(($rating[(int)$m['a1']]??2)+($rating[(int)$m['a2']]??2))/2;$rb=(($rating[(int)$m['b1']]??2)+($rating[(int)$m['b2']]??2))/2;$expectedA=1/(1+pow(10,$rb-$ra));$actualA=$winner==='A'?1.0:0.0;$factor=1+min(1.0,abs($sa-$sb)/11)*0.35;$deltaA=max(-0.18,min(0.18,0.14*($actualA-$expectedA)*$factor));foreach(['a1','a2'] as $c)$pdo->prepare("UPDATE players SET hidden_rating=GREATEST(1.00,LEAST(10.00,hidden_rating+?)),updated_at=NOW() WHERE id=?")->execute([$deltaA,$m[$c]]);foreach(['b1','b2'] as $c)$pdo->prepare("UPDATE players SET hidden_rating=GREATEST(1.00,LEAST(10.00,hidden_rating-?)),updated_at=NOW() WHERE id=?")->execute([$deltaA,$m[$c]]);$pdo->commit();v1320StartOnDeck($pdo,(int)$m['session_id']);v1320GenerateOnDeck($pdo,(int)$m['session_id']);
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
function v1320StartScheduledSession(PDO $pdo,int $sessionId,array $presentIds): void {
    $session=sessionById($pdo,$sessionId);if(!$session||$session['status']!=='scheduled')throw new Exception('Scheduled game is no longer available.');if(isCourtRental($session))throw new Exception('Court Rental does not start a Queue session.');$active=currentSession($pdo);if($active&&(int)$active['id']!==$sessionId)throw new Exception('Close the current active session first.');
    $nowDate=date('Y-m-d');$nowTime=date('H:i:s');$rq=$pdo->prepare("SELECT id,name,renter_name,scheduled_time,scheduled_end_time FROM sessions WHERE id<>? AND status='scheduled' AND schedule_type='court_rental' AND scheduled_date=? AND scheduled_time<=? AND scheduled_end_time>? LIMIT 1");$rq->execute([$sessionId,$nowDate,$nowTime,$nowTime]);if($r=$rq->fetch())throw new Exception('Court 1 is currently reserved for '.($r['renter_name']?:$r['name']).' until '.prettyTime($r['scheduled_end_time']).'. Open Play cannot start during a Court Rental.');
    $presentIds=array_values(array_unique(array_filter(array_map('intval',$presentIds))));$roster=array_flip(array_map('intval',array_column(rosterRows($pdo,$sessionId),'id')));$presentIds=array_values(array_filter($presentIds,fn($id)=>isset($roster[$id])));if(count($presentIds)<4)throw new Exception('Select at least 4 PRESENT players to start doubles play.');
    $pdo->beginTransaction();try{$pdo->prepare("DELETE FROM session_players WHERE session_id=?")->execute([$sessionId]);$ins=$pdo->prepare("INSERT INTO session_players(session_id,player_id,status,queue_credit,games_since_last_played) VALUES(?,?,'Waiting',?,0)");$order=0;foreach($presentIds as $pid)$ins->execute([$sessionId,$pid,++$order]);$pdo->prepare("UPDATE sessions SET status='active',started_at=NOW(),closed_at=NULL,updated_at=NOW() WHERE id=?")->execute([$sessionId]);$pdo->commit();v1320InitializeQueue($pdo,$sessionId);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
function v1320CreateScheduleRequest(PDO $pdo,array $data): int {
    $name=trim((string)($data['requester_name']??''));$contact=trim((string)($data['contact_number']??''));$type=($data['schedule_type']??'court_rental')==='open_play'?'open_play':'court_rental';$label=trim((string)($data['request_name']??''));$date=trim((string)($data['requested_date']??''));$start=normalizeTimeValue(trim((string)($data['requested_time']??'')));$end=normalizeTimeValue(trim((string)($data['requested_end_time']??'')));$notes=trim((string)($data['notes']??''));if($name==='')throw new Exception('Your name is required.');if($contact==='')throw new Exception('Contact details are required.');if(!scheduleWindowValid($date,$start,$end))throw new Exception('Choose a valid date and time range.');if(strtotime($date.' '.$end)<time())throw new Exception('Requested time must be in the future.');$q=$pdo->prepare("INSERT INTO schedule_requests(requester_name,contact_number,schedule_type,request_name,requested_date,requested_time,requested_end_time,notes,status,updated_at) VALUES(?,?,?,?,?,?,?,?,'pending',NOW())");$q->execute([$name,$contact,$type,$label,$date,$start,$end,$notes]);return (int)$pdo->lastInsertId();
}
function v1320ScheduleRequest(PDO $pdo,int $id): ?array {$q=$pdo->prepare("SELECT * FROM schedule_requests WHERE id=? LIMIT 1");$q->execute([$id]);return $q->fetch()?:null;}
function v1320PendingRequests(PDO $pdo,int $limit=50): array {$q=$pdo->prepare("SELECT * FROM schedule_requests WHERE status='pending' ORDER BY requested_date,requested_time,created_at LIMIT ?");$q->bindValue(1,$limit,PDO::PARAM_INT);$q->execute();return $q->fetchAll();}
function v1320RequestConflict(PDO $pdo,array $r): ?array {return scheduleConflict($pdo,(string)$r['requested_date'],(string)$r['requested_time'],(string)$r['requested_end_time']);}
function v1320ApproveRequest(PDO $pdo,int $id,array $override=[]): int {
    $r=v1320ScheduleRequest($pdo,$id);if(!$r||$r['status']!=='pending')throw new Exception('Request is no longer pending.');$data=['schedule_type'=>$override['schedule_type']??$r['schedule_type'],'name'=>trim((string)($override['request_name']??$r['request_name']??'')),'renter_name'=>$override['requester_name']??$r['requester_name'],'contact_number'=>$override['contact_number']??$r['contact_number'],'rental_fee'=>$override['rental_fee']??0,'amount_paid'=>$override['amount_paid']??0,'rental_notes'=>trim((string)($override['notes']??$r['notes']??'')),'scheduled_date'=>$override['requested_date']??$r['requested_date'],'scheduled_time'=>$override['requested_time']??$r['requested_time'],'scheduled_end_time'=>$override['requested_end_time']??$r['requested_end_time']];if($data['schedule_type']==='open_play'&&$data['name']==='')$data['name']='Requested Open Play - '.$r['requester_name'];$pdo->beginTransaction();try{$sid=saveSchedule($pdo,$data);$q=$pdo->prepare("UPDATE schedule_requests SET status='approved',reviewed_by_admin_id=?,reviewed_at=NOW(),approved_session_id=?,updated_at=NOW() WHERE id=?");$q->execute([(int)$_SESSION['admin_user_id'],$sid,$id]);$pdo->commit();return $sid;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
function v1320RejectRequest(PDO $pdo,int $id): void {$q=$pdo->prepare("UPDATE schedule_requests SET status='rejected',reviewed_by_admin_id=?,reviewed_at=NOW(),updated_at=NOW() WHERE id=? AND status='pending'");$q->execute([(int)$_SESSION['admin_user_id'],$id]);if(!$q->rowCount())throw new Exception('Request is no longer pending.');}
