function renderAlarms(){const el=$('alarmList');const active=alarms.filter(a=>a.lastAction!=='deleted');if(!active.length){el.innerHTML='<div class="card empty">No personal alarms yet. Tap + to create one.</div>';return}el.innerHTML=active.sort((a,b)=>(nextOccurrence(a)||Infinity)-(nextOccurrence(b)||Infinity)).map(a=>`<div class="card alarm"><div><div class="alarmTime">${fmtTime(a)}</div><div class="alarmTitle">${esc(a.title||'Reminder')}</div><div class="alarmDetails">${esc(a.details||repeatText(a))}</div><div>${pill(repeatText(a),repeats(a)?'red':'')}${a.important?pill('IMPORTANT','amber'):''}${pill(a.category||'General')}</div></div><div><input class="toggle alarmToggle" type="checkbox" ${a.enabled?'checked':''} data-id="${esc(a.id)}"><button class="btn ghost editAlarm" data-id="${esc(a.id)}" style="margin-top:8px">EDIT</button></div></div>`).join('');document.querySelectorAll('.alarmToggle').forEach(x=>x.onchange=()=>toggleAlarm(x.dataset.id,x.checked));document.querySelectorAll('.editAlarm').forEach(x=>x.onclick=()=>openEditor(x.dataset.id))}
async function syncPersonal(push=true){if(!session?.access_token)return;const payload=push?alarms.map(a=>({local_id:String(a.id).replace(/\D/g,'').slice(-15)||Date.now(),client_id:a.id,cloud_version:a.cloudVersion||0,title:a.title||'Reminder',details:a.details||'',scheduled_at:new Date(nextOccurrence(a)||Date.now()).toISOString(),status:a.lastAction==='deleted'?'deleted':a.enabled?'active':'done',enabled:!!a.enabled,important:!!a.important,vibrate:!!a.strongVibration,bypass:!!a.bypassSilent,repeat_days:a.days||[false,false,false,false,false,false,false],sound_uri:a.soundUri||'',base_hour:a.hour,base_minute:a.minute,timezone:'Asia/Manila',category:a.category||'General',last_action:a.lastAction||'edit',snooze_minutes:a.snoozeMinutes||0})):[];const rows=await af('/rest/v1/rpc/pulse_alarm_sync',{p_items:payload});if(!Array.isArray(rows))return;const mapped=rows.filter(r=>r.status!=='deleted').map(r=>({id:r.client_id||('cloud:'+r.id),title:r.title||'Reminder',details:r.details||'',hour:r.base_hour??new Date(r.scheduled_at).getHours(),minute:r.base_minute??new Date(r.scheduled_at).getMinutes(),days:Array.isArray(r.repeat_days)?r.repeat_days:[false,false,false,false,false,false,false],category:r.category||'General',important:!!r.important,enabled:r.enabled!==false,strongVibration:r.vibrate!==false,bypassSilent:!!r.bypass,soundUri:r.sound_uri||'Default',nextAt:new Date(r.scheduled_at).getTime(),oneShotAt:Array.isArray(r.repeat_days)&&r.repeat_days.some(Boolean)?0:new Date(r.scheduled_at).getTime(),lastAction:r.last_action||'edit',snoozeMinutes:r.snooze_minutes||0,cloudVersion:r.version||0}));const localDeleted=alarms.filter(a=>a.lastAction==='deleted');alarms=[...mapped,...localDeleted];saveLocal();renderAlarms()}
function toggleAlarm(id,on){const a=alarms.find(x=>x.id===id);if(!a)return;a.enabled=on;a.lastAction=on?'edit':'accomplish';if(on){const n=nextOccurrence(a,Date.now()-1000);if(n){a.nextAt=n;if(!repeats(a))a.oneShotAt=n}}saveLocal();renderAlarms();syncPersonal(true).catch(()=>{})}
function openEditor(id=null){const a=id?alarms.find(x=>x.id===id):blankAlarm();if(!a)return;$('editId').value=a.id;$('alarmTitleInput').value=a.title||'';$('alarmDetailsInput').value=a.details||'';$('alarmTimeInput').value=fmtTime(a);$('alarmCategoryInput').value=a.category||'General';$('importantInput').checked=!!a.important;$('vibrateInput').checked=a.strongVibration!==false;$('bypassInput').checked=!!a.bypassSilent;$('soundInput').value=a.soundUri||'Default';document.querySelectorAll('.day').forEach((b,i)=>b.classList.toggle('on',!!a.days?.[i]));$('deleteAlarmBtn').classList.toggle('hidden',!id);$('editor').classList.remove('hidden')}
function closeEditor(){$('editor').classList.add('hidden')}
function saveEditor(){const id=$('editId').value;let a=alarms.find(x=>x.id===id);if(!a){a=blankAlarm();a.id=id||('ios:'+Date.now());alarms.push(a)}const [h,m]=$('alarmTimeInput').value.split(':').map(Number);a.title=$('alarmTitleInput').value.trim()||'Reminder';a.details=$('alarmDetailsInput').value.trim();a.hour=h;a.minute=m;a.category=$('alarmCategoryInput').value.trim()||'General';a.important=$('importantInput').checked;a.strongVibration=$('vibrateInput').checked;a.bypassSilent=$('bypassInput').checked;a.soundUri=$('soundInput').value;a.days=[...document.querySelectorAll('.day')].map(b=>b.classList.contains('on'));a.enabled=true;a.lastAction='edit';const n=nextOccurrence(a,Date.now()-1000);a.nextAt=n||Date.now();a.oneShotAt=repeats(a)?0:(n||Date.now());saveLocal();renderAlarms();closeEditor();syncPersonal(true).catch(()=>{});addHistory(a.title+' • SAVED')}
function deleteEditor(){const a=alarms.find(x=>x.id===$('editId').value);if(!a)return;a.enabled=false;a.lastAction='deleted';saveLocal();renderAlarms();closeEditor();syncPersonal(true).catch(()=>{});addHistory(a.title+' • DELETED')}
function scheduleTicker(){if(timer)clearInterval(timer);timer=setInterval(checkDue,15000);checkDue()}
function checkDue(){const now=Date.now();for(const a of alarms){if(!a.enabled||a.lastAction==='deleted')continue;const n=a.nextAt||nextOccurrence(a);if(n&&n<=now+1000&&n>now-60000){startRing(a);break}}}
async function notifyAlarm(a){if('Notification'in window&&Notification.permission==='granted'&&navigator.serviceWorker){const reg=await navigator.serviceWorker.ready;reg.showNotification(a.title||'Pulse Alarm',{body:a.details||'Alarm is due',icon:'./icon.svg',badge:'./icon.svg',tag:'pulse-'+a.id,renotify:true,data:{alarmId:a.id}}).catch(()=>{})}}
function startRing(a){if(ringing)return;ringing=a;$('ringTitle').textContent=a.title||'REMINDER';$('ringDetails').textContent=a.details||'';$('ringTime').textContent=fmtTime(a);$('ringScreen').classList.remove('hidden');notifyAlarm(a);if(navigator.vibrate&&a.strongVibration)navigator.vibrate([500,250,500,250,800])}
function endRing(){if(navigator.vibrate)navigator.vibrate(0);$('ringScreen').classList.add('hidden');ringing=null}
function snooze(min){if(!ringing)return;const a=ringing;a.nextAt=Date.now()+min*60000;a.snoozeMinutes=min;a.lastAction='snooze';saveLocal();addHistory(a.title+' • SNOOZED '+min+' min');endRing();syncPersonal(true).catch(()=>{})}
function doneOccurrence(){if(!ringing)return;const a=ringing;addHistory(a.title+' • DONE');if(repeats(a)){a.nextAt=nextOccurrence(a,Date.now()+60000)||0}else{a.enabled=false;a.lastAction='done'}saveLocal();endRing();renderAlarms();syncPersonal(true).catch(()=>{})}
function accomplish(){if(!ringing)return;const a=ringing;a.enabled=false;a.lastAction='accomplish';addHistory(a.title+' • ACCOMPLISHED');saveLocal();endRing();renderAlarms();syncPersonal(true).catch(()=>{})}
