function renderHistory(){const el=$('historyList');if(!el)return;const h=getHistory();el.innerHTML=h.length?h.map(x=>`<div class="historyItem"><div>${esc(x.text)}</div><div class="meta">${new Date(x.at).toLocaleString()}</div></div>`).join(''):'<div class="empty">No alarm history yet.</div>'}
function setTab(tab){document.querySelectorAll('.tabPage').forEach(x=>x.classList.add('hidden'));$(tab+'Page').classList.remove('hidden');document.querySelectorAll('.nav button[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='workspace')loadAssignments().catch(()=>{});if(tab==='history')renderHistory()}
function setAuthMode(mode){const create=mode==='create';$('loginForm').classList.toggle('hidden',create);$('createAccountForm').classList.toggle('hidden',!create);$('showSignInBtn').classList.toggle('primary',!create);$('showSignInBtn').classList.toggle('ghost',create);$('showCreateBtn').classList.toggle('primary',create);$('showCreateBtn').classList.toggle('ghost',!create);$('authTitle').textContent=create?'Create Pulse Account':'Sign in';$('authHint').textContent=create?'Create your Pulse Account first so your alarms, employee identity and future workspace assignments can be saved to the Pulse database.':'Sign in to sync your personal alarms and employee workspace assignments.';$('loginStatus').textContent=''}
async function requestNotify(){const b=$('notifyBtn');b.disabled=true;$('notifyStatus').textContent='Enabling background notifications…';try{await enablePushNotifications();$('notifyStatus').textContent='Background notifications enabled on this device';b.textContent='ENABLED'}catch(e){$('notifyStatus').textContent=e.message}finally{b.disabled=false}}
function bindImportantHold(button,action,normalLabel){let started=0,clock=null;const reset=()=>{if(clock)clearInterval(clock);clock=null;button.textContent=normalLabel};button.addEventListener('pointerdown',e=>{if(!ringing)return;if(!ringing.important){action();return}started=Date.now();button.setPointerCapture?.(e.pointerId);clock=setInterval(()=>{const pct=Math.min(100,Math.round((Date.now()-started)/20));button.textContent='HOLD '+pct+'%';if(pct>=100){reset();action()}},80)});button.addEventListener('pointerup',()=>{if(ringing?.important&&Date.now()-started<2000)reset()});button.addEventListener('pointercancel',reset)}
$('showSignInBtn').onclick=()=>setAuthMode('signin');
$('showCreateBtn').onclick=()=>setAuthMode('create');
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const b=$('loginBtn');b.disabled=true;$('loginStatus').textContent='Signing in…';try{await signIn($('email').value,$('password').value);$('loginStatus').textContent=''}catch(err){$('loginStatus').textContent=err.message}finally{b.disabled=false}});
$('createAccountForm').addEventListener('submit',async e=>{e.preventDefault();const b=$('createAccountBtn');const p=$('createPassword').value,pc=$('createPasswordConfirm').value;if(p!==pc){$('loginStatus').textContent='Passwords do not match';return}const handle=$('createHandle').value.trim().toLowerCase().replace(/^@/,'');if(!/^[a-z0-9._-]{3,30}$/.test(handle)){$('loginStatus').textContent='Pulse @handle must be 3–30 characters using letters, numbers, dot, underscore or dash.';return}b.disabled=true;$('loginStatus').textContent='Creating Pulse Account…';try{const r=await signUp($('createEmail').value,p,$('createDisplayName').value,handle);$('loginStatus').textContent=r.message;if(!r.signedIn){$('email').value=$('createEmail').value;setAuthMode('signin');$('loginStatus').textContent=r.message}}catch(err){$('loginStatus').textContent=err.message}finally{b.disabled=false}});
$('logoutBtn').onclick=signOut;
$('addAlarmBtn').onclick=()=>openEditor();
$('closeEditorBtn').onclick=closeEditor;
$('saveAlarmBtn').onclick=saveEditor;
$('deleteAlarmBtn').onclick=deleteEditor;
$('notifyBtn').onclick=requestNotify;
$('refreshBtn').onclick=async()=>{try{$('syncStatus').textContent='Refreshing…';context=await af('/rest/v1/rpc/pulse_account_context',{});renderIdentity();await Promise.all([syncPersonal(true),loadAssignments(),refreshPushRegistration()]);$('syncStatus').textContent='Updated'}catch(e){$('syncStatus').textContent=e.message}};
$('joinBtn').onclick=joinWorkspace;
document.querySelectorAll('.day').forEach(b=>b.onclick=()=>b.classList.toggle('on'));
document.querySelectorAll('.nav button[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
$('s10').onclick=()=>snooze(10);
$('s30').onclick=()=>snooze(30);
$('sCustom').onclick=()=>{const v=Math.max(1,Math.min(180,Number(prompt('Snooze minutes (1-180)','60'))||60));snooze(v)};
bindImportantHold($('doneBtn'),doneOccurrence,'DONE');
bindImportantHold($('accomplishBtn'),accomplish,'ACCOMPLISH');
document.addEventListener('visibilitychange',()=>{if(!document.hidden){checkDue();if(session?.access_token){ensureFreshSession().then(()=>{syncPersonal(true).catch(()=>{});loadAssignments().catch(()=>{});refreshPushRegistration().catch(()=>{})}).catch(()=>{})}}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
loadLocal();renderAlarms();renderHistory();setAuthMode('signin');$('bottomNav').style.display='none';$('addAlarmBtn').style.display='none';restoreSession().then(ok=>{if(ok)return loadApp().then(()=>{if(typeof applyLaunchIntent==='function')applyLaunchIntent()});showSignedOut()}).catch(e=>{$('loginStatus').textContent='Could not restore session. Check your connection and try again.';showSignedOut()});
